services:
  web:   
    build:
      context: . 
    ports:
      - "5000:5000"      
    volumes:
      - .:/Webserver
    working_dir: /Webserver
    command: python app.py
    depends_on:
      - logger # Ensure logger service starts first

  logger:
    build:
      context: ../Logger
    ports: 
      - "5001:5001" 
    volumes:
      - ../Logger:/Logger    
    working_dir: /Logger
    command: python logger.py

